# Generated by Django 2.1.5 on 2019-01-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_name', models.CharField(max_length=32)),
                ('cookie_value', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='CookieJar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_csrf', models.CharField(max_length=24)),
                ('date_time_field', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('cellphone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_valid', models.BooleanField(default=True)),
                ('client_id', models.CharField(blank=True, max_length=15, null=True)),
                ('membership_exp_fitness', models.DateField(blank=True, null=True)),
                ('membership_exp_special', models.DateField(blank=True, null=True)),
                ('membership_exp_yoga', models.DateField(blank=True, null=True)),
                ('membership_ref_fitness', models.CharField(blank=True, max_length=15, null=True)),
                ('membership_ref_special', models.CharField(blank=True, max_length=15, null=True)),
                ('membership_ref_yoga', models.CharField(blank=True, max_length=15, null=True)),
                ('membership_type_fitness', models.CharField(blank=True, max_length=254, null=True)),
                ('membership_type_special', models.CharField(blank=True, max_length=254, null=True)),
                ('membership_type_yoga', models.CharField(blank=True, max_length=254, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('token_single', models.SmallIntegerField(default=5)),
            ],
        ),
    ]
