# Generated by Django 2.1.5 on 2019-01-13 22:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_booked_currently', models.BooleanField(default=False)),
                ('is_booked_previously', models.BooleanField(default=False)),
                ('is_late_cancelled', models.BooleanField(default=False)),
                ('is_listed', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_waitlisted', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_booked', models.DateTimeField(null=True)),
                ('date_cancelled', models.DateTimeField(null=True)),
                ('token_used', models.PositiveSmallIntegerField(default=1)),
                ('visit_id', models.CharField(blank=True, max_length=9)),
                ('waitlist_position', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitlist_update_time', models.DateTimeField(auto_now_add=True)),
                ('schedule_update_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.BookingRecord'),
        ),
        migrations.AddField(
            model_name='booking',
            name='class_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.ClassDetail'),
        ),
    ]
