# Generated by Django 2.2a1 on 2019-02-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_periodicbooking_token_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicbooking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
