# Generated by Django 2.1.5 on 2019-01-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_to_terms_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
