# Generated by Django 2.1.5 on 2019-01-13 22:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CenterSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=8)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Center')),
            ],
        ),
        migrations.CreateModel(
            name='ClassDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('class_id', models.CharField(blank=True, max_length=6)),
                ('start_time', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=50)),
                ('assistant', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('date_time_field', models.DateTimeField(null=True)),
                ('center_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.CenterSchedule')),
            ],
        ),
    ]
