# Generated by Django 2.2a1 on 2019-02-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_classdetail_class_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdetail',
            old_name='class_size',
            new_name='capacity',
        ),
    ]
