# Generated by Django 2.2a1 on 2019-02-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20190209_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetail',
            name='duration',
            field=models.CharField(max_length=30),
        ),
    ]
